<?php

namespace AppBundle\Repository;

/**
 * AsignacionGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
