<?php

namespace AppBundle\Repository;

/**
 * ConceptoSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
