<?php

namespace AppBundle\Repository;

/**
 * ConceptoImporteSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoImporteSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
