<?php

namespace AppBundle\Repository;

/**
 * ProyectoGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
