<?php

namespace AppBundle\Repository;

/**
 * SolicitudConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
